version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_tournoi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tournoi_flechettes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      timeout: 5s
      retries: 10
      interval: 5s
      start_period: 10s

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_tournoi
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=tournoi_flechettes
      - DATABASE_URL=mysql://user:password@mysql:3306/tournoi_flechettes
      - NODE_ENV=production
      - NEXT_DISABLE_ESLINT=1
      - NEXT_TELEMETRY_DISABLED=1

volumes:
  mysql_data: